#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.
pip install black flake8 flake518 isort ipython mypy neovim pydocstyle pylint pyright pre-commit
pre-commit install --install-hooks
