#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.
pip install black flake8 flake518 isort mypy neovim pydocstyle pylint pre-commit
pre-commit install --install-hooks

VENV=$(basename "$VIRTUAL_ENV")
cat > pyrightconfig.json << EOF
{
  "venv": "$VENV",
  "venvPath": "$WORKON_HOME"
}
EOF
