export CDPATH="$HOME/src"
# PATH
# generic
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/local/bin:$PATH"
# zsh
export ZSH="$HOME/.oh-my-zsh"
# brew
export HOMEBREW_NO_AUTO_UPDATE=0
# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
# pipenv
export PIPENV_VENV_IN_PROJECT=1
# pip user-installed binaries
export PATH="$(python3 -m site --user-base)/bin:${PATH}"
# Virtualenv Wrapper
export VIRTUALENVWRAPPER_PYTHON="/opt/homebrew/bin/python3"
export WORKON_HOME="$HOME/.virtualenvs"
# k9s
export K9S_CONFIG_DIR="$HOME/.config/k9s"

# LANGUAGE
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Set terminal to use 256 colors
export TERM="screen-256color"

# Custom pager & editor
export BAT_THEME="Monokai Extended Light"
export PAGER="/opt/homebrew/bin/less" # macos (native less missing lesskey)
export EDITOR="nvim"

# NVM
export NVM_DIR="$HOME/.nvm"

# FZF
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden' # Set fzf to use ripgrep
export FZF_DEFAULT_OPTS='--bind ctrl-r:up,ctrl-s:down' # BEPO mappings

# Java
export JAVA_HOME="/opt/homebrew/Cellar/openjdk@11/11.0.21/libexec/openjdk.jdk/Contents/Home"
