export CDPATH="$HOME:$CDPATH"
export CDPATH="$HOME/src:$CDPATH"
# PATH
# generic
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
# zsh
export ZSH="$HOME/.oh-my-zsh"
# brew
export HOMEBREW_NO_AUTO_UPDATE=1
# pip user-installed binaries
export PATH="$(python3 -m site --user-base)/bin:${PATH}"
# k9s
export K9S_CONFIG_DIR="$HOME/.config/k9s"
# breakpoint in python
export PYTHONBREAKPOINT="ipdb.set_trace"

# LANGUAGE
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Custom pager & editor
export BAT_THEME="Monokai Extended Light"
export EDITOR="nvim"

# NVM
export NVM_DIR="$HOME/.nvm"

# FZF
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden' # Set fzf to use ripgrep
export FZF_DEFAULT_OPTS='--bind ctrl-r:up,ctrl-s:down' # BEPO mappings

# GPG
export GPG_TTY=$(tty)

# Java
export JAVA_HOME="/opt/homebrew/Cellar/openjdk@11/11.0.25/libexec/openjdk.jdk/Contents/Home"
