# Add user-installed binaries to PATH
export PATH="/usr/local/bin:$PATH"
# Prepare NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# ZSH theme. See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"

# Use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# ZSH plugins to load
# Repo must be cloned in .oh-my-zsh/plugins if it is not done by default
plugins=( git fzf pyenv zsh-syntax-highlighting )
source $ZSH/oh-my-zsh.sh
source $ZSH/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#Overwrite some git plugin aliases
alias gcm="git commit -m"
alias gcom="git checkout master"

# You may need to manually set your language environment
export LANG="en_US.UTF-8"
# Set terminal to use 256 colors
export TERM="screen-256color"
# Custom pager for man pages
export PAGER="most"

# Custom aliases that doesn't fit elsewhere
alias tmux="direnv exec / tmux" # Make sure direnv is unloaded before exec tmux
alias letsgo="pipenv install neovim" # For virtual environments setup
alias tiga="tig --all"

# Create function used in direnv .envrc to setup PROMPT
show_virtual_env() {
    if [[ -n "$VIRTUAL_ENV" && -n "$DIRENV_DIR" ]]; then
        echo "(${$(basename $VIRTUAL_ENV)%-*})"
    fi
}
export PROMPT=%{%F{red}%}$(show_virtual_env)$PROMPT

# Hook direnv into shell
eval "$(direnv hook zsh)"

# Show only username in prompt
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
  fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
